### ISSUE TITLE
Add a way to abort requests

### ISSUE THREAD

**Issue by miduga** [cferdinandi/atomic#20]
Atomic lacks a way to abort the current ajax requests. Useful, for example, when an user is using autocomplete functions and you want to abort previous requests to save resources and time.

It would be great to have something like that.

```
var ajaxRequest = atomic.get( "/endpoint" );
// aborting the request
ajaxRequest.abort();
```

**Comment by toddmotto** [comment]
Hey dude, won't be able to push something for at least a month or so, absolutely stacked. PRs are welcome though if you'd like to discuss implementation! :)

**Comment by miduga** [comment]
Sure. I'll take a look. :) Thanks for the reply!

**Comment by cferdinandi** [comment]
A year and a half later, added! https://github.com/cferdinandi/atomic/pull/51
