### ISSUE TITLE
ActiveXObject is not defined

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [cferdinandi/atomic#22]
Hi!

The following code fails with 'Uncaught ReferenceError: ActiveXObject is not defined' message:

```
import * as atomic from 'atomic';

atomic.get(url.file)
  .success(function(data, xhr) {
    console.log('.success:', data, xhr);
  })
  .error(function(data, xhr) {
    console.log('.error:', data, xhr);
  })
  .always(function(data, xhr) {
    console.log('.always:', data, xhr);
  });
```

PS:
I'm using Babel + Webpack.

**Comment by selenir** [comment]
https://github.com/toddmotto/atomic/blob/master/dist/atomic.js#L6
Try replacing `module.exports = factory;` with `module.exports = factory(root);`

**Comment by lvnhmd** [comment]
Hello, did the above actually work ? I am having the same problem, thank you.

**Comment by cferdinandi** [comment]
The UMD header was wrong. @lvnhmd, do you want to try updating to v1.2.0 (from [this just merged PR](https://github.com/toddmotto/atomic/pull/28)) and see if works now?
