### ISSUE TITLE
How to use Atomic properly (Browserify & Babel)

### ISSUE THREAD

**Issue by dvLden** [cferdinandi/atomic#25]
I tried to use Atomic as a dependency of my project and it was all good, until I wanted to make a change and start using Browserify and Babel. So before it worked fine as:

```
<script src="js/plugins/atomic.js"></script>
<script>
    atomic.get('/endpoint').success({});
</script>
```

But... Now it gives me error and throw me to line `35` as `root is undefined`.
`var XHR = root.XMLHttpRequest || ActiveXObject;`

The way I call it is:

```
import atomic from './plugins/atomic';

atomic.get('/endpoint').success({});
```

So that is failing... But this is working:

```
import atomic from './plugins/atomic';

const AJAX = atomic(window);

AJAX.get('/endpoint').success({});
```

Is that proper way of using it or is there a better way? I think I may be doing something wrong, so just making sure...

**Comment by cferdinandi** [comment]
The UMD header was wrong on versions 1.1.0 and lower. [This just merged PR](https://github.com/toddmotto/atomic/pull/28) should fix this issue.
