### ISSUE TITLE
Add ability to set headers map

### ISSUE THREAD

**Issue by Karl-Gustav** [cferdinandi/atomic#27]
I'm sorry if this is already possible but I could't find it in the source code, but if it is possible this issue should be for adding it to the documentation.

**Comment by cferdinandi** [comment]
Just took this over from Todd. Can you clarify what you're looking for, please?

**Comment by Karl-Gustav** [comment]
I just wanted a way to set headers on the request. Like Authorization or Content-Type.

But this is issue not important for me anymore, never got a reply so I just made my own: https://github.com/Karl-Gustav/atto-ajax/blob/master/README.md

**Comment by cferdinandi** [comment]
Very helpful, thanks! I know you've already implemented your own solution, but I like it better than how things are setup now, and will likely implement this into Atomic. Cheers!

**Comment by cferdinandi** [comment]
Will be addressed by https://github.com/cferdinandi/atomic/pull/40
