### ISSUE TITLE
Add "X-Requested-With" header to request

### ISSUE THREAD

**Issue by pistom** [cferdinandi/atomic#29]
to detecting ajax/non-ajax request on the server side
`request.setRequestHeader('X-Requested-With', 'XMLHttpRequest');`

**Comment by cferdinandi** [comment]
I'm not sure what you mean. Details please?

**Comment by pistom** [comment]
Hi,
By receiving this request header, we can guess that the request is xhttprequest or standard and we can prepare a specific response.
https://davidwalsh.name/detect-ajax

**Comment by cferdinandi** [comment]
@pistom In looking at that, it appears to be PHP specific. Is that relevant to this script, which is always an xml http request?

**Comment by pistom** [comment]
Hi Chris, 
no, it is not php-specific.
http://stackoverflow.com/questions/17478731/whats-the-point-of-the-x-requested-with-header
http://stackoverflow.com/questions/21749461/where-does-the-http-request-header-x-requested-with-come-from

**Comment by cferdinandi** [comment]
Cool, thanks for the extra info. I definitely think I can support this. I believe the most extensible way to support this and other header types is through an open ended option as described here: https://github.com/cferdinandi/atomic/issues/27

I should be implementing this in the next week or so. Stay tuned!

**Comment by pistom** [comment]
Thank you.

**Comment by cferdinandi** [comment]
Will be addressed by https://github.com/cferdinandi/atomic/pull/40
