### ISSUE TITLE
Add support for data input as a string

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/atomic#36]
Currently only supports an object.

**Comment by cferdinandi** [comment]
Unneeded bloat

**Comment by I-CRE8** [comment]
I respectfully disagree with the unneeded bloat comment, if you are serialising form data you get a string and this could then be passed as you would in native javascript

**Comment by cferdinandi** [comment]
@I-CRE8 Fair point, but... why wouldn't/couldn't you just append said string to the end of the URL?

**Comment by I-CRE8** [comment]
@cferdinandi because I mostly POST rather than GET

**Comment by cferdinandi** [comment]
*Technically* you could still send that data along as a query string, but... I'm convinced.

**Comment by I-CRE8** [comment]
Thank you

**Comment by cferdinandi** [comment]
Supported with https://github.com/cferdinandi/atomic/pull/46
