### ISSUE TITLE
add the ability to make ajax calls with credentials

### ISSUE THREAD

**Issue by cultulhul** [cferdinandi/atomic#37]
add the ability to make ajax calls with credentials, currently i have to add a withCredentials = true line just after the XMLHttpRequest object has been created

**Comment by cferdinandi** [comment]
Haven't forgotten about this! Been focused on a few other projects but absolutely intended to implement this.

**Comment by cferdinandi** [comment]
Hey there! Just added this to v3.1.0. https://github.com/cferdinandi/atomic/pull/42
