### ISSUE TITLE
IE8 .delete() method quirk

### ISSUE THREAD

**Issue by toddmotto** [cferdinandi/atomic#5]
With IE8, any methods named `.delete()` will throw an error. AngularJS also has the same "problem" in IE8. Using a delete method using Object dot notation will error your application.

The workaround is very simple, using bracket notation lookup rather than dot notation:

``` js
atomic['delete']
.success()
.error();
```

**Comment by cferdinandi** [comment]
Fixed, sort of, as the script no longer uses request type specific methods.
