### ISSUE TITLE
Add support for onprogress callback

### ISSUE THREAD

**Issue by threethousand** [cferdinandi/atomic#52]
Would be amazing if the upload progress event could be added. Will help building upload progress bars. 
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload

**Comment by cferdinandi** [comment]
Nice feature request! Just [pushed v3.4.0](https://github.com/cferdinandi/atomic/pull/53), which exposes a the original XHR request. You can use this to add event listeners and call root properties like `upload`.

```js
// Make your call
var xhr = atomic.ajax({
	url: '/endpoint'
}).success(function (data) {
	// ...
});

// Access the request
xhr.request.addEventListener('load', function () {
	console.log('Loaded!');
}, false);
```
