### ISSUE TITLE
Specifying 'Content-Type': 'application/x-www-form-urlencoded' will not automatically convert an object to that type.

### ISSUE THREAD

**Issue by ajdrausal** [cferdinandi/atomic#54]
`if (/application\/json/i.test(settings.headers['Content-type']) || Object.prototype.toString.call(obj) === '[object Array]') return JSON.stringify(obj);`

If the user specifies the content-type as 'Content-Type': 'application/x-www-form-urlencoded' I think the library should ignore the object type.

**Comment by cferdinandi** [comment]
Can you share a bit more information about why this is needed and/or what it does?

Thanks!

**Comment by ajdrausal** [comment]
Here in your code you have a check that I believe is not handling Content-Type specified by the user.

`var param = function (obj) {
		if (typeof (obj) === 'string') return obj;
		if (/application\/json/i.test(settings.headers['Content-type']) || Object.prototype.toString.call(obj) === '[object Array]') return JSON.stringify(obj);
		var encoded = [];
		for (var prop in obj) {
			if (obj.hasOwnProperty(prop)) {
				encoded.push(encodeURIComponent(prop) + '=' + encodeURIComponent(obj[prop]));
			}
		}
		return encoded.join('&');
	};`


If want to send an encoded URL and pass in straight object data like this bellow, I can't.
`
let URL = "SomeURL";
let d = {"Value1" : "Value1Data", "Value2" :  "Value2Data" };
//d is Object
var r = atomic({
        url:'URL',
        method:'POST', 
        data : d,
        headers: {'Content-Type': 'application/x-www-form-urlencoded'},
         
        
    });
`

I have to first 

`
var formBody = [];
for (var property in d) {
  var encodedKey = encodeURIComponent(property);
  var encodedValue = encodeURIComponent(d[property]);
  formBody.push(encodedKey + "=" + encodedValue);
}
`

And then pass in formBody in the data field

**Comment by cferdinandi** [comment]
Thanks! I can see how this is not quite working as expected in Atomic. From MDN:

> The parameter to the send() method can be any data you want to send to the server if POST-ing the request. Form data should be sent in a format that the server can parse, like a query string:
>
> ```
> "name=value&anothername="+encodeURIComponent(myVar)+"&so=on"
> ```
>
> or other formats, like multipart/form-data, JSON, XML, and so on.

I'll fix this, but can't guarantee any sort of completion date given some other priorities at the moment. Your fix addresses your specific use case, but I think there are some broader format issues I'm missing.

**Comment by cferdinandi** [comment]
Reading up a bit more on this, it looks like if you want to send straight JSON data, `application/json` is the correct type. Otherwise, it needs to be encoded into a string to send.

I'm closing this, as I believe the current implementation is correct.
