### ISSUE TITLE
Why does feature test postulates native code for promises?

### ISSUE THREAD

**Issue by rekrut** [cferdinandi/atomic#66]
We cannot longer use a polyfill for promises since v4.0.0 to get "atomic" work in browsers that haven't a native support of promises.

**Comment by cferdinandi** [comment]
> Smooth Scroll uses semantic versioning.

- https://github.com/cferdinandi/atomic#migrating-from-atomic-3
- https://github.com/cferdinandi/atomic#1-include-atomic-on-your-site
- https://github.com/cferdinandi/atomic#browser-compatibility

**Comment by rekrut** [comment]
Please have a look here:
https://github.com/cferdinandi/atomic/blob/d7c911d66edd9ff00ae3b2282b9981556420c72d/src/js/atomic.js#L45

The condition `Promise.toString().indexOf('[native code]') !== -1` avoids the use of a polyfill

**Comment by cferdinandi** [comment]
Ah gotcha. Good catch!

Just pushed v4.2.1, which fixes this.

**Comment by rekrut** [comment]
Great - Thank you!
