### ISSUE TITLE
Add a way to set default options

### ISSUE THREAD

**Issue by garygreen** [cferdinandi/atomic#68]
Just like you can with jQuery's `$.ajaxSetup()` or various ways to set [axios defaults](https://github.com/axios/axios#config-defaults)

This would be very useful for when you want to always send e.g. CSRF token or certain headers, etc.

**Comment by cferdinandi** [comment]
You could save your options to a var and pass that in?

I'm not open to supporting this feature at this time. Sorry!

**Comment by garygreen** [comment]
> You could save your options to a var and pass that in?

The main problem comes with merging the default options with the custom options your using for the request. You have a `extend` function built into atomic which already handles it. Not sure why your not open to supporting the feature which would add zero bloat to the library, it's just a case of allowing consumers to access the `defaults` of atomic...

**Comment by garygreen** [comment]
I'll just fork the library and hack away on it with various features as you don't seem very open to suggestions. Grateful for all your work on the library though, it's super awesome 😄

**Comment by cferdinandi** [comment]
I've incorporated a lot of community suggestions. I'm just unsure about this specific approach adding any value.

I'm honestly failing to see how `atomic.get(url)` or `atomic.post(url)` are easier/better than `atomic(url, {method: 'post'})` Feels more like a personal preference thing, no?

**Comment by cferdinandi** [comment]
This seems to only make sense in the context of https://github.com/cferdinandi/atomic/issues/69. Otherwise, I'm not sure how this is any more efficient than setting your options to a variable for reuse.

**Comment by garygreen** [comment]
```js
atomic('https://test.com/users/save', { method: 'POST', headers: { 'Custom-Header': 'blah' }});
```

How would you merge the default headers with your custom ones as above? You would need to some a deep merge of some kind. That functionality is already inside Atomic so it would be nice to leverage that, somehow.
