### ISSUE TITLE
Consider adding common method shortcuts

### ISSUE THREAD

**Issue by garygreen** [cferdinandi/atomic#69]
Would be awesome if common methods could be added:

```js
atomic.post('https://www.test.com', [data], [config]).then(...)
atomic.get('https://www.test.com', [data], [config]).then(...)
```

This is much nicer and more explicit than doing:

```js
atomic('https://www.test.com', { method: 'POST' })
atomic('https://www.test.com')
```

(I realise `get` is shorter as it's the default method, but it's worth adding for consistency)

This might coincide with #68 if you could get the atomic instance and call methods / set defaults etc.

**Comment by cferdinandi** [comment]
I'd recommend checking out Axios, which seems like more like what you're looking for. 

Additions like this add weight to the code, which is currently nice and lightweight. 

https://github.com/axios/axios

**Comment by garygreen** [comment]
Yah, it would maybe add 100 bytes for the benefit of every user. 99.999% of people will be using `.get()` or `.post()`, it would be a nice addition. axios is still around 5KB gzipped this library is 1KB gzipped 😄

**Comment by cferdinandi** [comment]
I've incorporated a lot of community suggestions. I'm just unsure about this specific approach adding any value.

I'm honestly failing to see how `atomic.get(url)` or `atomic.post(url)` are easier/better than `atomic(url, {method: 'post'})` Feels more like a personal preference thing, no?

**Comment by garygreen** [comment]
You could argue it's personal preference but to me it's more down to developer satisfaction and experience. For the sake of a few extra bytes, you can write more expressive code that is both easier to write and read. It might not make much of a difference for the odd ajax call here and there, but across a codebase that relies heavily on API calls, it can make a big difference to clarity and visual debt.

Imagine you had the same thing in a routing system:

```php
Route::method('POST', '...');
Route::method('GET', '...');
```

Rather than

```php
Route::post('...');
Route::get('...');
```

I would put money on the fact that the majority of developers would much prefer to use the terser `.get` or `.post` than `{ method: 'post' }` (the latter is probably preferred when you dynamically decide if you want to do a post/get request, though).

It also helps with integrations with editors as it opens up the possibility of easily seeing the api methods rather than hiding them behind some generic objects with options.

I guess it's a different philosophy to one your currently using with Atomic, which is why I'm considering maintaining a separate fork and will likely re-structure the code and go with a more OOD approach and add a few convenience methods (such as this) to make it even more pleasant to use.
