### ISSUE TITLE
add additional headers

### ISSUE THREAD

**Issue by cms09** [cferdinandi/atomic#7]
Maybe it would be nice to have an option to add additional headers.
For example to send a token to an API.

Maybe like jQuery:

atomic.get('someUrl', {
   headers: {
        "My-First-Header":"first value",
        "AuthToken":"xxxxxxx"
    }
});

**Comment by CanRau** [comment]
Long time, but readme doesn't say anything about additional headers, any news on it?

**Comment by toddmotto** [comment]
Hey @cms09, I'm super stacked at the moment, would you be interested in submitting a PR to add the behaviour? Cheers! :)
