### ISSUE TITLE
Push current version to npm

### ISSUE THREAD

**Issue by brandonkal** [cferdinandi/atomic#72]
Please push the current version to npm and update the readme to suggest using the jsdelivr npmjs urls over the /gh/ urls as they recommend.

Thanks for this library!

**Comment by cferdinandi** [comment]
I made a hard break with v4.x away from NPM.

With dozens of OSS projects to maintain, adding another step to the deploy process is something I just constantly forget to do, etc.

Once GitHub Actions rollout (which can be used to automate NPM deployment) I will revisit.

**Comment by Log1x** [comment]
You haven't happened to get access to GitHub Actions beta yet, have you? You have some seriously great libraries– I really hope to see them all on npm soon..

**Comment by cferdinandi** [comment]
Thanks for the bump, @Log1x! I *have* gotten access, actually!

I got a bit stuck on how to set things up. I believe I need to add my NPM credentials to an environment variable somewhere.

If you've seen any tutorials around this, I'm all ears. I'd love to set this up!

**Comment by Log1x** [comment]
I haven't worked with them personally yet, but it looks like GitHub has provided an action specifically for npm: https://github.com/actions/npm

Thanks a lot!

**Comment by cferdinandi** [comment]
The token piece (and specifically how not to expose that publicly) are what's got me stuck right now. Soon as I figure that out, I'm golden!

**Comment by cferdinandi** [comment]
Oh, here we go! https://medium.com/devopslinks/automate-your-npm-publish-with-github-actions-dfe8059645dd

**Comment by Log1x** [comment]
I wasn't entirely sure how the actions worked– I was wrongly assuming it was an local var. The above looks like it will integrate nicely!

Another project that might be worth a global install is [np](https://github.com/sindresorhus/np).

**Comment by cferdinandi** [comment]
Yet, I can't get it to work. Just pushed a new version with updated tag and... nothing on NPM. Not sure what's going on here... :(

**Comment by Log1x** [comment]
Does the action namespace it (e.g. @cferdinandi/atomic)? I know there's another `atomic` package that already exists, could be clashing and failing silently or something.

**Comment by cferdinandi** [comment]
it's `atomicjs` there. I updated the name in `package.json` first. I must have the action messed up.

**Comment by cferdinandi** [comment]
Ok, this was REALLY convoluted, but I think I've got it working, finally. Thanks for the push
