### ISSUE TITLE
X-Requested-With

### ISSUE THREAD

**Issue by moloclab** [cferdinandi/atomic#86]
"X-Requested-With: XMLHttpRequest" is not present in the Request Header? Why? 
It would be useful to identify ajax request server side.

Thanks!

**Comment by cferdinandi** [comment]
I try to keep Atomic as minimal as possible, and not everyone needs that. You can add it yourself with the `headers` option, though: https://github.com/cferdinandi/atomic#options-and-settings

**Comment by moloclab** [comment]
Thanks, work like a charm!
