### ISSUE TITLE
Use Promise-like syntax

### ISSUE THREAD

**Issue by toddmotto** [cferdinandi/atomic#9]
As well as the `.success()` and `.error()` methods, potentially provide a promise-like syntax:

``` js
atomic.get()
.then(function () {
  // success
}, function () {
  // error
});
```

**Comment by cferdinandi** [comment]
Just took this project over from Todd, and in the interest of backwards compatibility, I'm closing this as wontfix.

Yes, I could polyfill it, but then that adds a bunch of additional weight to the project. Sorry!

**Comment by cferdinandi** [comment]
After being stubborn about this for a year, I've had a change of heart. Atomic is now Promise-based, supporting `.then()` chaining, with `.catch()` for error handling.
